name: home_service
description: Home Service Provider App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
#  sdk: ">=2.12.0 <3.0.0"
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  pull_to_refresh: ^2.0.0
  # GET
#  get: 4.3.8
  get: ^4.6.1
  get_storage: 2.0.3
  get_it: ^7.2.0
  # DIO
  dio: 4.0.3
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: 2.1.0
  auto_size_text: 3.0.0
  #IMAGES, SLIDERS, LAYOUTS
  cached_network_image: 3.1.0+1
  carousel_slider: 4.0.0
#  flutter_svg: 0.22.0
  flutter_staggered_grid_view: 0.4.1
  image_picker: 0.8.4+4
  flutter_image_compress: ^1.1.3
  cupertino_icons: any
  # WEB
  webview_flutter: 2.3.1
  url_launcher: 6.1.11
  flutter_html: 2.2.1
  # FIREBASE
#  firebase_messaging: 11.1.0
  firebase_messaging:
  cloud_firestore: 4.14.0
  firebase_auth:
  firebase_core: 2.24.2
  firebase_storage:
  # GOOGLE MAPS
#  google_maps_flutter: 2.1.1
#  map_launcher: 2.1.1
  map_launcher: ^2.5.0+1
  #hexcolor: ^3.0.1
  flutter:
    sdk: flutter
#  flutter_localizations:
#    sdk: flutter
  flutter_localization: ^0.1.13

#  pusher_channels_flutter: ^2.2.0
  pusher_client: ^2.0.0
#  connectycube_flutter_call_kit: ^2.0.5
  connectycube_sdk: ^2.1.1
  shared_preferences: ^2.0.6
  shared_preferences_ios:
  shared_preferences_android:

  #platform_device_id: ^1.0.1
  universal_io: ^2.0.4
  web_browser_detect: ^2.0.2
#  flutter_background: ^1.1.0
  permission_handler: ^9.2.0
  device_info_plus: 4.0.0 #^3.2.3
  html_unescape: ^2.0.0

  no_context_navigation: ^2.1.2
  #loading_gifs not used in user app
  loading_gifs: ^0.3.0
  flutter_ringtone_player: ^3.2.0
  #overlay_support not used in user app
  overlay_support: ^2.0.1
  #flutter_local_notifications not used in user app
  flutter_local_notifications: ^9.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: 0.0.1+3
  place_picker: ^0.10.0
  fan_carousel_image_slider: ^0.1.2


dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:


flutter:
  uses-material-design: true

  assets:
    - config/
    - assets/img/
    - assets/screens/
    - assets/icon/
    - assets/locales/
    - assets/sounds/
